### PR TITLE
Add test_status and exception. Remove feature and feature_group.

### PR DESCRIPTION
**Pull request by kgilpin**

### CODE REVIEW

**Review by dividedmind — CHANGES_REQUESTED** [review]
Needs changelog entry. Maybe a version bump?

**Comment by dividedmind** [comment]
Also, there are other test statuses possible. `pending` comes to mind.

**Comment by dividedmind** [comment]
Another thought: it's not entirely clear if `test_status` should be present if a test errors out -- and if so, what value it should have.

**Comment by dividedmind** [comment]
> Also, there are other test statuses possible. For example, in pytest tests can xfail (expected failure) or xpass (unexpected pass).

Actually, nevermind that. While trying to implement it I realized it's not really that important in an appmap; it really deals with test runners and reporters rather than tests themselves, so is at another level of abstraction. Plus it can be quite difficult to capture. Perhaps there's value in being generic about it.

**Comment by kgilpin** [comment]
I could see:

succeeded
failed
error

But to be honest, everything except Succeeded is basically going to be
treated the same by any downstream analytics.

Mostly what we want to know is if the AppMap represents a new “known good
state” or not.

**Comment by kgilpin** [comment]
For example, to run incremental AppMap updates, we want to run:

Any new test
Any non-succeeded test
Any test that has a modified dependency (a file path listed in the classmap
is more recently modified than the AppMap)

**Review by dividedmind — APPROVED** [review]

**Pull request merged**
